name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: shogo82148/actions-setup-redis@v1
      with:
           redis-version: '6.x'

    - name: installing add on packages
      run: sudo apt install gcc-4.8 g++-4.8 python3-pip libbz2-dev ccache zlib1g-dev uuid-dev

    - name: installing dependencies
      run: npm ci
      env:
        PHANTOMJS_CDNURL: http://cnpmjs.org/downloads

    - name: installing codecov
      run: npm i -g codecov

    - name: installing devtools
      run: dev/install-zimtools.sh

    - name: building
      run: npm run build

    - name: running test with codecov
      run: REDIS=redis://127.0.0.1:6379 ZIMCHECK_PATH=`find .. -name zimcheck` npm run codecov

    - name: running test
      run: npm run jest

    - name: publishing script
      run: ./dev/publish.sh

    - name: codecov action
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
