# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:

    runs-on: ubuntu-latest
    services:
        redis:
            image: redis
            ports:
            - 6379:6379

    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo apt install gcc-4.8 g++-4.8 python3-pip libbz2-dev ccache zlib1g-dev uuid-dev
    - run: npm ci
    - run: npm i -g codecov
    - run: dev/install-zimtools.sh
    - run: npm run build --if-present
    - run: npm run lint
    - run: npm run build
    - run: REDIS=redis://127.0.0.1:6379 ZIMCHECK_PATH=`find .. -name zimcheck` npm run codecov
    - run: npm run jest
    - run: npm test
    - run: ./dev/publish.sh
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
